export const data = {
  OutsideData: [
    { option: '2 to 1' },
    { option: '2 to 1' },
    { option: '2 to 1' },
    { option: '1st 12' },
    { option: '2nd 12' },
    { option: '3rd 12' },
    { option: '1 to 18' },
    { option: 'EVEN' },
    { option: 'RED' },
    { option: 'BLACK' },
    { option: 'ODD' },
    { option: '19 to 36' }
  ],
  InsideData: [
    { option: '0', style: { backgroundColor: 'green', textColor: 'white' } },
    { option: '32', style: { backgroundColor: 'red', textColor: 'white' } },
    { option: '15', style: { backgroundColor: 'black', textColor: 'white' } },
    { option: '19', style: { backgroundColor: 'red', textColor: 'white' } },
    { option: '4', style: { backgroundColor: 'black', textColor: 'white' } },
    { option: '21', style: { backgroundColor: 'red', textColor: 'white' } },
    { option: '2', style: { backgroundColor: 'black', textColor: 'white' } },
    { option: '25', style: { backgroundColor: 'red', textColor: 'white' } },
    { option: '17', style: { backgroundColor: 'black', textColor: 'white' } },
    { option: '34', style: { backgroundColor: 'red', textColor: 'white' } },
    { option: '6', style: { backgroundColor: 'black', textColor: 'white' } },
    { option: '27', style: { backgroundColor: 'red', textColor: 'white' } },
    { option: '13', style: { backgroundColor: 'black', textColor: 'white' } },
    { option: '36', style: { backgroundColor: 'red', textColor: 'white' } },
    { option: '11', style: { backgroundColor: 'black', textColor: 'white' } },
    { option: '30', style: { backgroundColor: 'red', textColor: 'white' } },
    { option: '8', style: { backgroundColor: 'black', textColor: 'white' } },
    { option: '23', style: { backgroundColor: 'red', textColor: 'white' } },
    { option: '10', style: { backgroundColor: 'black', textColor: 'white' } },
    { option: '5', style: { backgroundColor: 'red', textColor: 'white' } },
    { option: '24', style: { backgroundColor: 'black', textColor: 'white' } },
    { option: '16', style: { backgroundColor: 'red', textColor: 'white' } },
    { option: '33', style: { backgroundColor: 'black', textColor: 'white' } },
    { option: '1', style: { backgroundColor: 'red', textColor: 'white' } },
    { option: '20', style: { backgroundColor: 'black', textColor: 'white' } },
    { option: '14', style: { backgroundColor: 'red', textColor: 'white' } },
    { option: '31', style: { backgroundColor: 'black', textColor: 'white' } },
    { option: '9', style: { backgroundColor: 'red', textColor: 'white' } },
    { option: '22', style: { backgroundColor: 'black', textColor: 'white' } },
    { option: '18', style: { backgroundColor: 'red', textColor: 'white' } },
    { option: '29', style: { backgroundColor: 'black', textColor: 'white' } },
    { option: '7', style: { backgroundColor: 'red', textColor: 'white' } },
    { option: '28', style: { backgroundColor: 'black', textColor: 'white' } },
    { option: '12', style: { backgroundColor: 'red', textColor: 'white' } },
    { option: '35', style: { backgroundColor: 'black', textColor: 'white' } },
    { option: '3', style: { backgroundColor: 'red', textColor: 'white' } },
    { option: '26', style: { backgroundColor: 'black', textColor: 'white' } },
  ]
}
